# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: msbuild d3dlearn.sln -p:Configuration=Debug -p:Platform=x64
  displayName: 'Build debug version'
- publish: x64/Debug
  artifact: Debug
- script: msbuild d3dlearn.sln -p:Configuration=Release -p:Platform=x64
  displayName: 'Build release version'
- publish: x64/Release
  artifact: Release
