# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: MSBuild@1
  inputs:
    solution: '**/*.sln' 
    msbuildArchitecture: 'x64'
- publish: x64/Debug
  artifact: Debug
- publish: x64/Release
  artifact: Release
